-- ==============================================================
-- IoT Lab Monitor - SQL Schema untuk Supabase (PostgreSQL)
-- Copy dan paste seluruh query ini ke SQL Editor di Supabase Anda.
-- ==============================================================

-- Hapus tabel jika sudah ada (untuk reset data)
DROP TABLE IF EXISTS data_sensor;
DROP TABLE IF EXISTS ruangan;

-- 1. Membuat tabel 'ruangan'
CREATE TABLE ruangan (
    id_ruangan GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_ruangan TEXT NOT NULL,
    laboratorium TEXT CHECK (laboratorium IN ('Lab 1', 'Lab 2')) NOT NULL,
    kode_sensor TEXT UNIQUE NOT NULL, -- Contoh: LAB1_R01, LAB2_R25
    deskripsi TEXT
);

-- 2. Membuat tabel 'data_sensor'
CREATE TABLE data_sensor (
    id_data BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_sensor TEXT REFERENCES ruangan(kode_sensor) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
    suhu REAL NOT NULL,
    kelembapan REAL NOT NULL,
    waktu TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 3. Membuat Index untuk performa
CREATE INDEX idx_data_sensor_waktu ON data_sensor(waktu DESC);
CREATE INDEX idx_data_sensor_kode ON data_sensor(kode_sensor);

-- 4. Memasukkan data master 24 Ruangan di Laboratorium Terpadu 1 (Lab 1)
INSERT INTO ruangan (nama_ruangan, laboratorium, kode_sensor, deskripsi) VALUES
('Workshop B - Perakitan (R102)', 'Lab 1', 'LAB1_R01', 'Laboratorium Terpadu 1'),
('Lab. Rekayasa Konstruksi dan Transportasi (R103)', 'Lab 1', 'LAB1_R02', 'Laboratorium Terpadu 1'),
('Lab Uji Destruktif dan Non Destruktif (R104)', 'Lab 1', 'LAB1_R03', 'Laboratorium Terpadu 1'),
('Lab. Teknologi Proses (R105)', 'Lab 1', 'LAB1_R04', 'Laboratorium Terpadu 1'),
('Lab. Sistem Tenaga Listrik dan Otomasi (R106)', 'Lab 1', 'LAB1_R05', 'Laboratorium Terpadu 1'),
('Lab. Karakterisasi A (R107)', 'Lab 1', 'LAB1_R06', 'Laboratorium Terpadu 1'),
('Lab. Karakterisasi B (R108)', 'Lab 1', 'LAB1_R07', 'Laboratorium Terpadu 1'),
('Lab. Termal (R109)', 'Lab 1', 'LAB1_R08', 'Laboratorium Terpadu 1'),
('Lab. Kimia Dasar A (R201)', 'Lab 1', 'LAB1_R09', 'Laboratorium Terpadu 1'),
('Lab. Fisika Dasar', 'Lab 1', 'LAB1_R10', 'Laboratorium Terpadu 1'),
('Kantor Administrasi A (R203)', 'Lab 1', 'LAB1_R11', 'Laboratorium Terpadu 1'),
('Kantor Administrasi B (R204)', 'Lab 1', 'LAB1_R12', 'Laboratorium Terpadu 1'),
('Ruang Kerja Bersama (R205)', 'Lab 1', 'LAB1_R13', 'Laboratorium Terpadu 1'),
('Ruang Kerja Bersama (R206)', 'Lab 1', 'LAB1_R14', 'Laboratorium Terpadu 1'),
('Workshop A - Manufaktur (R101)', 'Lab 1', 'LAB1_R15', 'Laboratorium Terpadu 1'),
('Lab. Kimia Dasar B (R208)', 'Lab 1', 'LAB1_R16', 'Laboratorium Terpadu 1'),
('Lab. Komputer A (R301)', 'Lab 1', 'LAB1_R17', 'Laboratorium Terpadu 1'),
('Lab. Komputer B (R302)', 'Lab 1', 'LAB1_R18', 'Laboratorium Terpadu 1'),
('Lab. Komputer C (R303)', 'Lab 1', 'LAB1_R19', 'Laboratorium Terpadu 1'),
('Lab. Komputer D (R304)', 'Lab 1', 'LAB1_R20', 'Laboratorium Terpadu 1'),
('Lab. Komputer E (R305)', 'Lab 1', 'LAB1_R21', 'Laboratorium Terpadu 1'),
('Lab. Komputer F (R306)', 'Lab 1', 'LAB1_R22', 'Laboratorium Terpadu 1'),
('Lab. Komputer G (R307)', 'Lab 1', 'LAB1_R23', 'Laboratorium Terpadu 1'),
('Lab. Karakterisasi C (R101)', 'Lab 1', 'LAB1_R24', 'Laboratorium Terpadu 1');

-- 5. Memasukkan data master 25 Ruangan di Laboratorium Terpadu 2 (Lab 2)
INSERT INTO ruangan (nama_ruangan, laboratorium, kode_sensor, deskripsi) VALUES
('Lab. Operasi Teknologi Kimia (R102)', 'Lab 2', 'LAB2_R01', 'Laboratorium Terpadu 2'),
('Lab. Rekayasa Lingkungan dan Pengolahan Limbah (R103)', 'Lab 2', 'LAB2_R02', 'Laboratorium Terpadu 2'),
('Lab. Rekayasa Industri dan Ergonomi (R106)', 'Lab 2', 'LAB2_R03', 'Laboratorium Terpadu 2'),
('Lab. Rekayasa Keselamatan (R107)', 'Lab 2', 'LAB2_R04', 'Laboratorium Terpadu 2'),
('Lab. Proses Produksi 1 (R108)', 'Lab 2', 'LAB2_R05', 'Laboratorium Terpadu 2'),
('Lab. Proses Produksi 2 DT & NDT (R108)', 'Lab 2', 'LAB2_R06', 'Laboratorium Terpadu 2'),
('Lab. Permesinan dan Konversi Energi (R109)', 'Lab 2', 'LAB2_R07', 'Laboratorium Terpadu 2'),
('Lab. Konstruksi Bangunan Laut (R115)', 'Lab 2', 'LAB2_R08', 'Laboratorium Terpadu 2'),
('Lab. Geoteknik dan Ukur Tanah (R116)', 'Lab 2', 'LAB2_R09', 'Laboratorium Terpadu 2'),
('Lab. Hidrodinamika dan Aerodinamika (R118)', 'Lab 2', 'LAB2_R10', 'Laboratorium Terpadu 2'),
('Lab. Pusat Penelitian Energi (R201)', 'Lab 2', 'LAB2_R11', 'Laboratorium Terpadu 2'),
('Lab. Kimia Material (R202)', 'Lab 2', 'LAB2_R12', 'Laboratorium Terpadu 2'),
('Lab. Pusat Penelitian Pangan Pertanian (R203)', 'Lab 2', 'LAB2_R13', 'Laboratorium Terpadu 2'),
('Lab. Teknologi Pangan (R204)', 'Lab 2', 'LAB2_R14', 'Laboratorium Terpadu 2'),
('Kantor Administrasi (R205)', 'Lab 2', 'LAB2_R15', 'Laboratorium Terpadu 2'),
('Lab Logistik & Manajemen Rantai Pasok (R206)', 'Lab 2', 'LAB2_R16', 'Laboratorium Terpadu 2'),
('Ruang Seminar (R207)', 'Lab 2', 'LAB2_R17', 'Laboratorium Terpadu 2'),
('Lab Fisika Lanjut (R301)', 'Lab 2', 'LAB2_R18', 'Laboratorium Terpadu 2'),
('Lab Elektronika dan Robotika (R302)', 'Lab 2', 'LAB2_R19', 'Laboratorium Terpadu 2'),
('Lab Komputasi Tinggi (R303)', 'Lab 2', 'LAB2_R20', 'Laboratorium Terpadu 2'),
('Lab Telekomunikasi dan Jaringan Komputer (R304)', 'Lab 2', 'LAB2_R21', 'Laboratorium Terpadu 2'),
('Lab Pengembangan Perangkat Lunak (R305)', 'Lab 2', 'LAB2_R22', 'Laboratorium Terpadu 2'),
('Studio Perencanaan Tata Ruang (R306)', 'Lab 2', 'LAB2_R23', 'Laboratorium Terpadu 2'),
('Studio Arsitektur dan Desain (R307)', 'Lab 2', 'LAB2_R24', 'Laboratorium Terpadu 2'),
('Lab Pusat Penelitian Smart City (R308)', 'Lab 2', 'LAB2_R25', 'Laboratorium Terpadu 2');
